#! python3

import openpyxl, sys
from openpyxl.styles import Font

# Assign 'dim' variable to argument given when calling program
dim = sys.argv[1]

# Create new workbook
wb = openpyxl.Workbook()
# Set 'sheet' to active sheet in workbook
sheet = wb.active

# Iterate through first column and first row to set initial values and make them bold
for n in range(1, int(dim) + 1):
	sheet.cell(row=1, column=n+1).value = n
	sheet.cell(row=1, column=n+1).font = Font(name='Calibri', bold=True)
	sheet.cell(row=n+1, column=1).value = n
	sheet.cell(row=n+1, column=1).font = Font(name='Calibri', bold=True)

# Iterate through each row and column in the given area and multiply by each column and row header
for i in range(2, int(dim) + 2):
	for j in range(2, int(dim) + 2):
		sheet.cell(row=i, column=j).value = sheet.cell(row=i, column=1).value * sheet.cell(row=1, column=j).value
	
# Save workbook
wb.save('MultTable.xlsx')
